import { useSession } from "next-auth/react"
import Head from "next/head"
import * as React from "react"
import Sidebar from "../sidebar"
import RightBar from '../rightBar'
export interface IAppProps {
  children: React.ReactNode
  selected: string
}

export default function App(props: IAppProps) {
  const { data: session, status } = useSession()
  const loading = status === "loading"
  const [content, setContent] = React.useState()

  React.useEffect(() => {
    const fetchData = async () => {
      const res = await fetch("/api/examples/protected")
      const json = await res.json()
      if (json.content) {
        setContent(json.content)
      }
    }
    fetchData()
  }, [session])

  // When rendering client side don't display anything until loading is complete
  if (typeof window !== "undefined" && loading) return null

  return (
    <div>
      <Head>
        <title>Ledger | Manage your portfolio effectively</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/droheqpxn/image/upload/v1642427169/ledger/Logo_vovqso.png"
        />
      </Head>
      <RightBar/>
      <Sidebar selected={props.selected} />
      {session && props.children}
    </div>
  )
}
